# Generated by Django 4.2.19 on 2025-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_media',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
