[phases.setup]
nixPkgs = ["python39", "gcc", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn blogPost.wsgi:application --bind 0.0.0.0:$PORT --log-file -"