# Generated by Django 4.2.19 on 2025-02-17 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_blog_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_media',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
