# Generated by Django 4.2.19 on 2025-02-17 18:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_blog_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=250)),
                ('event_subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('event_body', models.CharField(blank=True, max_length=1500, null=True)),
                ('event_madia1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('event_madia2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('event_madia3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_body',
            field=models.CharField(max_length=1500),
        ),
    ]
