# Generated by Django 4.2.19 on 2025-02-19 22:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_events_alter_blogpost_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
