# Generated by Django 4.2.19 on 2025-02-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_video_id_alter_blogpost_blog_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='video_id',
            new_name='video_url',
        ),
    ]
