# Generated by Django 4.2.19 on 2025-02-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_video_id_blogpost_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='video_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
