# Generated by Django 4.2.19 on 2025-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_madia2',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_madia3',
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_venue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
