# Generated by Django 4.2.19 on 2025-02-20 13:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_events_event_madia2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_madia1',
        ),
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
