# Generated by Django 4.2.19 on 2025-02-20 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_events_event_madia1_events_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
