# Generated by Django 4.2.19 on 2025-02-23 15:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_events_event_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('leader_id', models.AutoField(primary_key=True, serialize=False)),
                ('leader_name', models.CharField(max_length=400)),
                ('leader_title', models.CharField(max_length=400)),
                ('leader_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
