# Generated by Django 4.2.19 on 2025-02-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_leaders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaders',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='leaders',
            table='leaders',
        ),
    ]
