# Generated by Django 4.2.19 on 2025-03-01 23:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_like_count_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='like_count',
        ),
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='anonymous_user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('anonymous_user_id', 'post')},
        ),
        migrations.AlterModelTable(
            name='like',
            table=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='blog_post',
        ),
    ]
