# Generated by Django 4.2.19 on 2025-03-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_like_options_remove_blogpost_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
