# Generated by Django 4.2.19 on 2025-03-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogpost_created_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
