# Generated by Django 4.2.19 on 2025-03-04 23:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_events_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageBackground',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('background_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'db_table': 'aboutBackground',
                'managed': True,
            },
        ),
    ]
