# Generated by Django 4.2.19 on 2025-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_aboutpagebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaders',
            name='leader_branch',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
