# Generated by Django 4.2.19 on 2025-03-12 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_leaders_leader_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
